name: "yoyo"
server:
  host: "0.0.0.0"
  port: 8080
  base_path: "/api"
db:
  dns: "yoyo:yoyo@tcp(localhost:3306)/yoyo?charset=utf8mb4,utf8&parseTime=True&loc=Local"
  logger:
    level: info
logger:
  rolling_file:
    base_dir: "./logs"
resource_dir: "./data"
